name: "datawise-build-generic-docker"
description: "datawise build and push generic container"
inputs: 
  PROJECT: 
    required: true
  APP:
    required: true
  SERVICE:
    required: true    
  INSTANCE:
    required: true
  VERSION:
    required: true
  DOCKER_REPOSITORY_BASE:
    required: true
    default: "docker.datawise.ai"
  DOCKER_USER: 
    required: true
    default: "builder"
  DOCKER_PASS:
    required: true
runs:
  using: "composite"
  steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: setup docker context for buildx
      id: buildx-context
      shell: bash       
      run: |
        docker context create builders || true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        endpoint: builders

    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.PROJECT }}.${{ inputs.DOCKER_REPOSITORY_BASE }}
        username: builder
        password: ${{ inputs.DOCKER_PASS }}

    #- uses: actions/checkout@v2

    - name: Build and push container
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.PROJECT }}.${{ inputs.DOCKER_REPOSITORY_BASE }}/${{ inputs.APP }}-${{ inputs.SERVICE }}-${{ inputs.INSTANCE }}:${{ inputs.VERSION }}      
          ${{ inputs.PROJECT }}.${{ inputs.DOCKER_REPOSITORY_BASE }}/${{ inputs.APP }}-${{ inputs.SERVICE }}-${{ inputs.INSTANCE }}:latest
        cache-from:
          ${{ inputs.PROJECT }}.${{ inputs.DOCKER_REPOSITORY_BASE }}/${{ inputs.APP }}-${{ inputs.SERVICE }}-${{ inputs.INSTANCE }}:latest

          



